version: '3.8'
services:
  apache_php_service:
    build: apache_php
    container_name: apache_php
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./apache_php/src:/var/www/html
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
